import type { Metadata } from 'next'
import '../globals.css'
import Header from '@/components/ui/Header/header'

import React from 'react'

export const metadata: Metadata = {
  title: 'Ontask',
  description: 'Generated by create next app'
}

export default function Layout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Header />
      <main>{children}</main>
    </>
  )
}
