import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import Footer from "@/components/Footer/footer"
import { ThemeProvider } from "@/components/Theme/theme-provider"
import { cn } from "@/lib/utils"
import PageScroll from "@/components/PageScroll/PageScroll"
import ClientWrapper from "@/components/Loader/ClientWrapper"

const vazirRegular = localFont({
  src: "./fonts/vazir/Vazirmatn-Regular.woff2",
  variable: "--font-vazir-regular",
  weight: "400"
})

const vazirBold = localFont({
  src: "./fonts/vazir/Vazirmatn-Bold.woff2",
  variable: "--font-vazir-bold",
  weight: "700"
})

const vazirLight = localFont({
  src: "./fonts/vazir/Vazirmatn-Light.woff2",
  variable: "--font-vazir-light",
  weight: "300"
})

export const metadata: Metadata = {
  title: "Ontask",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body
        className={cn(
          "flex min-h-screen flex-col bg-background font-vazir antialiased",
          vazirRegular.variable,
          vazirBold.variable,
          vazirLight.variable
        )}
      >
        <ClientWrapper>
          <PageScroll />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="grow">{children}</main>
            <Footer />
          </ThemeProvider>
        </ClientWrapper>
      </body>
    </html>
  )
}
