import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Header from '@/components/ui/Header/header'
import Footer from '@/components/ui/Footer/footer'
import { ThemeProvider } from '@/components/ui/Theme/theme-provider'
import { cn } from '@/lib/utils'

const vazirRegular = localFont({
  src: './fonts/vazir/Vazirmatn-Regular.woff2',
  variable: '--font-vazir-regular',
  weight: '100 900'
})

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900'
// })
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900'
// })

export const metadata: Metadata = {
  title: 'Ontask',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='fa' dir='rtl' suppressHydrationWarning>
      <body
        className={cn(
          'font-vazir mx-auto flex min-h-screen flex-col bg-background antialiased md:w-[800px] lg:w-[1000px]',
          vazirRegular.variable
          // geistSans.variable,
          // geistMono.variable
        )}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main className='grow'>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
