import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Footer from '@/components/ui/Footer/footer'
import { ThemeProvider } from '@/components/ui/Theme/theme-provider'
import { cn } from '@/lib/utils'
import PageScroll from '@/components/PageScroll/PageScroll'
import ClientWrapper from '@/components/Loader/ClientWrapper'

const vazirRegular = localFont({
  src: './fonts/vazir/Vazirmatn-Regular.woff2',
  variable: '--font-vazir-regular',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'Ontask',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='fa' dir='rtl' suppressHydrationWarning>
      <body
        className={cn(
          'mx-auto flex min-h-screen flex-col bg-background font-vazir antialiased',
          vazirRegular.variable
        )}
      >
        <ClientWrapper>
          <PageScroll />
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <main className='grow md:mx-auto md:w-[700px] lg:w-[1000px]'>
              {children}
            </main>
            <Footer />
          </ThemeProvider>
        </ClientWrapper>
      </body>
    </html>
  )
}
